#!/usr/bin/env python3
import os
import sys
import argparse
import subprocess

def parse_args():
    p = argparse.ArgumentParser(
        description='BasicVSR++ central‐frame fusion (4K)')
    p.add_argument('--input_folder', type=str, required=True,
                   help='Folder with N input frames (PNG/JPG)')
    p.add_argument('--output_path', type=str, required=True,
                   help='Where to save the fused central frame')
    p.add_argument('--checkpoint', type=str,
                   default='basicvsr_plusplus/checkpoints/'
                           'basicvsr_plusplus_c64n7_8x1_600k_reds4.pth',
                   help='Path to the REDS4 checkpoint')
    p.add_argument('--device', type=str, default='cuda',
                   help='“cuda” or “cpu”')
    return p.parse_args()

def main():
    args = parse_args()
    demo = os.path.join('basicvsr_plusplus', 'demo', 'restoration_video_demo.py')
    if not os.path.isfile(demo):
        sys.exit(f'ERROR: cannot find demo script at {demo}')

    # temp output dir
    tmp_out = 'tmp_enhanced'
    os.makedirs(tmp_out, exist_ok=True)

    cmd = [
        sys.executable, demo,
        '--input_folder',  args.input_folder,
        '--output_folder', tmp_out,
        '--checkpoint_file', args.checkpoint,
        '--device', args.device
    ]
    print('📡  Running the official BasicVSR++ demo…')
    subprocess.check_call(cmd)

    # pick out the central frame
    frames = sorted(f for f in os.listdir(tmp_out)
                    if f.lower().endswith(('.png','jpg','jpeg')))
    if not frames:
        sys.exit('ERROR: no frames generated by demo')

    central = frames[len(frames)//2]
    src = os.path.join(tmp_out, central)
    os.makedirs(os.path.dirname(args.output_path), exist_ok=True)
    os.replace(src, args.output_path)

    print(f'✔️  Saved enhanced central frame to {args.output_path}')

if __name__ == '__main__':
    main()
